"""Generate the ATT&CK coverage view of the rule set.

Two artefacts come out of this:

* ``docs/attack-coverage.md`` - a table a hiring manager or a detection lead can
  read without any tooling.
* ``build/attack-navigator-layer.json`` - a layer file that can be dropped into
  the MITRE ATT&CK Navigator to see the same thing on the matrix.

Coverage is counted from the rules themselves, so it cannot drift away from what
is actually deployed. An unmapped technique tag fails the build, because a tag
that is not a real technique quietly breaks every coverage claim built on it.
"""

from __future__ import annotations

import argparse
import json
import sys
from collections import defaultdict
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
RULES_DIR = REPO_ROOT / "rules"
CACHE = Path(__file__).resolve().parent / "attack_techniques.json"
DOC_OUT = REPO_ROOT / "docs" / "attack-coverage.md"
LAYER_OUT = REPO_ROOT / "build" / "attack-navigator-layer.json"

STIX_URL = (
    "https://raw.githubusercontent.com/mitre-attack/attack-stix-data/"
    "master/enterprise-attack/enterprise-attack.json"
)


def load_cache() -> dict:
    return json.loads(CACHE.read_text(encoding="utf-8"))


def refresh_cache() -> None:
    """Rebuild the technique cache from MITRE's published STIX bundle."""
    import urllib.request

    print(f"fetching {STIX_URL} ...")
    with urllib.request.urlopen(STIX_URL) as response:  # noqa: S310 - fixed, trusted URL
        bundle = json.load(response)

    data = load_cache()
    techniques: dict[str, str] = {}
    for obj in bundle.get("objects", []):
        if obj.get("type") != "attack-pattern" or obj.get("revoked") or obj.get("x_mitre_deprecated"):
            continue
        for ref in obj.get("external_references", []):
            if ref.get("source_name") == "mitre-attack" and ref.get("external_id", "").startswith("T"):
                techniques[ref["external_id"]] = obj.get("name", "")
    data["techniques"] = dict(sorted(techniques.items()))
    CACHE.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8", newline="\n")
    print(f"cached {len(techniques)} techniques")


def collect() -> tuple[dict[str, list[dict]], dict[str, list[dict]], list[str]]:
    """Return (techniques -> rules, tactics -> rules, unknown tags)."""
    cache = load_cache()
    known_techniques = cache["techniques"]
    known_tactics = cache["tactics"]

    by_technique: dict[str, list[dict]] = defaultdict(list)
    by_tactic: dict[str, list[dict]] = defaultdict(list)
    unknown: list[str] = []

    for path in sorted(RULES_DIR.rglob("*.yml")):
        raw = yaml.safe_load(path.read_text(encoding="utf-8"))
        entry = {
            "title": raw.get("title", path.stem),
            "path": path.relative_to(REPO_ROOT).as_posix(),
            "level": raw.get("level", "unknown"),
            "status": raw.get("status", "unknown"),
        }
        for tag in raw.get("tags") or []:
            tag = str(tag)
            if not tag.startswith("attack."):
                continue
            value = tag[len("attack.") :]
            if value.startswith("t"):
                technique = value.upper()
                if technique not in known_techniques:
                    unknown.append(f"{path.name}: unknown technique {technique}")
                    continue
                by_technique[technique].append(entry)
            else:
                if value not in known_tactics:
                    unknown.append(f"{path.name}: unknown tactic {value}")
                    continue
                by_tactic[value].append(entry)

    return by_technique, by_tactic, unknown


def write_markdown(by_technique: dict[str, list[dict]], by_tactic: dict[str, list[dict]]) -> None:
    cache = load_cache()
    lines = [
        "# ATT&CK coverage",
        "",
        "Generated by `tools/coverage_map.py`. Do not edit by hand; run `make coverage`.",
        "",
        "## By technique",
        "",
        "| Technique | Name | Rules |",
        "| --- | --- | --- |",
    ]
    for technique in sorted(by_technique):
        rules = by_technique[technique]
        names = "<br>".join(f"`{r['path']}`" for r in rules)
        lines.append(f"| {technique} | {cache['techniques'][technique]} | {names} |")

    lines += ["", "## By tactic", "", "| Tactic | Rule count |", "| --- | --- |"]
    for tactic in sorted(by_tactic):
        lines.append(f"| {cache['tactics'][tactic]} | {len(by_tactic[tactic])} |")

    total = len({r["path"] for rules in by_technique.values() for r in rules})
    lines += [
        "",
        f"Techniques covered: **{len(by_technique)}** across **{total}** rules.",
        "",
        "Coverage counts techniques with at least one rule. It is a map of where",
        "detections exist, not a claim that those techniques are fully detected -",
        "one rule for a technique with a dozen procedures covers one procedure.",
        "",
    ]
    DOC_OUT.parent.mkdir(parents=True, exist_ok=True)
    DOC_OUT.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"wrote {DOC_OUT.relative_to(REPO_ROOT)}")


def write_layer(by_technique: dict[str, list[dict]]) -> None:
    layer = {
        "name": "detection-as-code coverage",
        "versions": {"attack": "17", "navigator": "5.1.0", "layer": "4.5"},
        "domain": "enterprise-attack",
        "description": "Techniques with at least one rule in this repository.",
        "techniques": [
            {
                "techniqueID": technique,
                "score": len(rules),
                "comment": "\n".join(r["title"] for r in rules),
                "enabled": True,
            }
            for technique, rules in sorted(by_technique.items())
        ],
        "gradient": {"colors": ["#d7eaf9", "#1f6feb"], "minValue": 0, "maxValue": 3},
        "legendItems": [],
    }
    LAYER_OUT.parent.mkdir(parents=True, exist_ok=True)
    LAYER_OUT.write_text(json.dumps(layer, indent=2) + "\n", encoding="utf-8", newline="\n")
    print(f"wrote {LAYER_OUT.relative_to(REPO_ROOT)}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--refresh", action="store_true", help="re-fetch technique names from MITRE")
    parser.add_argument("--check", action="store_true", help="fail if the generated doc is stale")
    args = parser.parse_args()

    if args.refresh:
        refresh_cache()

    by_technique, by_tactic, unknown = collect()
    if unknown:
        for problem in unknown:
            print(f"[FAIL] {problem}")
        return 1

    previous = DOC_OUT.read_text(encoding="utf-8") if DOC_OUT.exists() else ""
    write_markdown(by_technique, by_tactic)
    write_layer(by_technique)

    if args.check and DOC_OUT.read_text(encoding="utf-8") != previous:
        print("[FAIL] docs/attack-coverage.md was out of date; commit the regenerated file")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
